# Generated by Django 2.1 on 2018-08-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_users', '0002_auto_20180820_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
