# Generated by Django 2.1 on 2018-08-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_users', '0003_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
